version: "3.3"
services:
  spark-master:
    build: .
    container_name: docker-spark
    ports:
      - "8082:8082"  # Map the new Master web UI port to host
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    command: ["/bin/bash", "/start-spark.sh"]

  spark-worker:
    build: .
    container_name: hduser-spark-worker
    ports:
    - "8083:8083"

    environment:
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_WORKLOAD=worker

    command: ["/bin/bash", "/start-spark.sh"]
